
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class FormPrecioso extends javax.swing.JFrame {
    private MineralPrecioso precioso;
    private BDMineralPrecioso bdMPrec = new BDMineralPrecioso();
    /**
     * Creates new form FormPrecioso
     */
    public FormPrecioso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTitulo = new javax.swing.JLabel();
        lblCodIdentificador = new javax.swing.JLabel();
        cxCodIdentificador = new javax.swing.JTextField();
        LNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        LCor = new javax.swing.JLabel();
        cxCor = new javax.swing.JTextField();
        LCompQuimica = new javax.swing.JLabel();
        cxCompQuimica = new javax.swing.JTextField();
        LDureza = new javax.swing.JLabel();
        cxDureza = new javax.swing.JTextField();
        LPeso = new javax.swing.JLabel();
        cxPeso = new javax.swing.JTextField();
        LValorComercial = new javax.swing.JLabel();
        cxValorComercial = new javax.swing.JTextField();
        LCertificado = new javax.swing.JLabel();
        cxCertificado = new javax.swing.JTextField();
        LRefinamento = new javax.swing.JLabel();
        cxRefinamento = new javax.swing.JTextField();
        InfOrigem = new javax.swing.JLabel();
        LPais = new javax.swing.JLabel();
        cxPais = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        cxCidade = new javax.swing.JTextField();
        lbTipExtracao = new javax.swing.JLabel();
        cxTipExtracao = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrecioso = new javax.swing.JTable();
        jButtonAlterar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LTitulo.setText("Cadastra Mineral Precioso");

        lblCodIdentificador.setText("Codigo Identificador");

        cxCodIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCodIdentificadorActionPerformed(evt);
            }
        });

        LNome.setText("Nome");

        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        LCor.setText("Cor");

        cxCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCorActionPerformed(evt);
            }
        });

        LCompQuimica.setText("Composicao Química");

        cxCompQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCompQuimicaActionPerformed(evt);
            }
        });

        LDureza.setText("Dureza");

        cxDureza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDurezaActionPerformed(evt);
            }
        });

        LPeso.setText("Peso");

        cxPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPesoActionPerformed(evt);
            }
        });

        LValorComercial.setText("Valor Comercial");

        cxValorComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxValorComercialActionPerformed(evt);
            }
        });

        LCertificado.setText("Certificado");

        cxCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCertificadoActionPerformed(evt);
            }
        });

        LRefinamento.setText("Refinamento");

        cxRefinamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxRefinamentoActionPerformed(evt);
            }
        });

        InfOrigem.setText("Informações de Origem");

        LPais.setText("País");

        cxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPaisActionPerformed(evt);
            }
        });

        lbCidade.setText("Cidade");

        cxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCidadeActionPerformed(evt);
            }
        });

        lbTipExtracao.setText("Tipo de Extração");

        cxTipExtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTipExtracaoActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("Consultar pelo Codigo Identificador");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jTablePrecioso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Identificador", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        jScrollPane1.setViewportView(jTablePrecioso);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButton2.setText("Execluir pelo Codigo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LValorComercial)
                                .addComponent(LDureza)
                                .addComponent(LPeso)
                                .addComponent(LCor)
                                .addComponent(LNome)
                                .addComponent(lblCodIdentificador)
                                .addComponent(cxValorComercial, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addComponent(cxPeso)
                                .addComponent(cxDureza)
                                .addComponent(cxCompQuimica)
                                .addComponent(cxCor)
                                .addComponent(cxNome)
                                .addComponent(cxCodIdentificador))
                            .addComponent(LTitulo)
                            .addComponent(LCompQuimica))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(LPais)
                                                            .addComponent(lbCidade)
                                                            .addComponent(lbTipExtracao))
                                                        .addGap(177, 177, 177))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(LCertificado)
                                                            .addComponent(LRefinamento))
                                                        .addGap(196, 196, 196)))
                                                .addComponent(cxCertificado)
                                                .addComponent(cxPais)
                                                .addComponent(cxCidade)
                                                .addComponent(cxTipExtracao)
                                                .addComponent(cxRefinamento))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btCadastrar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                                .addComponent(jButtonAlterar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(InfOrigem)
                                        .addGap(102, 102, 102))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButtonConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTitulo)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LCertificado)
                        .addGap(4, 4, 4)
                        .addComponent(cxCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LRefinamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxRefinamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InfOrigem))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(cxCodIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCodIdentificador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LCor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LCompQuimica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxCompQuimica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LPeso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LDureza)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cxDureza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(LValorComercial)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cxValorComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btLimpar)
                                    .addComponent(btCadastrar)
                                    .addComponent(btSair)
                                    .addComponent(jButtonAlterar)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LPais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbCidade)
                                .addGap(4, 4, 4)
                                .addComponent(cxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTipExtracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxTipExtracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPaisActionPerformed

    private void cxCodIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCodIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCodIdentificadorActionPerformed

    private void cxCompQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCompQuimicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCompQuimicaActionPerformed

    private void cxCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCorActionPerformed

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void cxRefinamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxRefinamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxRefinamentoActionPerformed

    private void cxCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCertificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCertificadoActionPerformed

    private void cxValorComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxValorComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxValorComercialActionPerformed

    private void cxPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPesoActionPerformed

    private void cxDurezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDurezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDurezaActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrar();
        listarTab();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void cxTipExtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTipExtracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxTipExtracaoActionPerformed

    private void cxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCidadeActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        alterar();
        listarTab();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        excluirCod();
        listarTab();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void excluirCod(){
        precioso= new MineralPrecioso();
        try{
        precioso.setCodIdentificador(Integer.parseInt(cxCodIdentificador.getText()));
        precioso=bdMPrec.remvMPrecioso(precioso);
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Formato Errado Informado", "Cadastro Mineral Precioso", 0);    
        }
    }
    public void alterar(){
        precioso = new MineralPrecioso();
        
        try{
            precioso.setCodIdentificador(Integer.parseInt(cxCodIdentificador.getText()));
            precioso=bdMPrec.atualPrecioso(precioso);
            if(precioso != null){
                cxCodIdentificador.setText(Integer.toString(precioso.getCodIdentificador()));
                cxNome.setText(precioso.getNome());
                JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso", "Atualizar Dados", 1);
                
            }
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Formato Errado Informado", "Cadastro Mineral Precioso", 0);    
        }
    }
    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) jTablePrecioso.getModel();
        
        int posLin=0;
        
        modelo.setRowCount(posLin);
        
        for(MineralPrecioso precioso : bdMPrec.getBdMprec()){
            modelo.insertRow(posLin, new Object[]{
                precioso.getCodIdentificador(),
                precioso.getNome(),
                precioso.getCor(),
                precioso.getComposicaoQuimica(),
                precioso.getDureza(),
                precioso.getPeso(),
                precioso.getValorComercial(),
                precioso.getCertificado(),
                precioso.getRefinamento(),
                precioso.getOrigem().getPais(),
                precioso.getOrigem().getCidade(),
                precioso.getOrigem().getTipo_Extracao(),
            });
            posLin++;
        }
    }
    public void limpar(){
        cxCodIdentificador.setText("");
        cxNome.setText("");
        cxCor.setText("");
        cxCompQuimica.setText("");
        cxDureza.setText("");
        cxPeso.setText("");
        cxValorComercial.setText("");
        cxCertificado.setText("");
        cxRefinamento.setText("");
        cxPais.setText("");
        cxCidade.setText("");
        cxTipExtracao.setText("");
        cxNome.requestFocus();
    }    public void cadastrar(){
        precioso=  new MineralPrecioso();
        
        precioso.setCodIdentificador(Integer.parseInt(cxCodIdentificador.getText()));
        precioso.setNome(cxNome.getText());
        precioso.setCor(cxCor.getText());
        try{
                precioso.setComposicaoQuimica(cxCompQuimica.getText());
                precioso.setDureza(Integer.parseInt(cxDureza.getText()));
                precioso.setPeso(Float.parseFloat(cxPeso.getText()));
                precioso.setValorComercial(Double.parseDouble(cxValorComercial.getText()));
        }
        catch(ComposicaoQGrdException cge){
                cge.impCQGrd();
                
        }
        catch(DurezaPqnException dpe){
                dpe.impDPqn();
                precioso = dpe.corDPqn(precioso);
        }
        catch(DurezaGrdException dge){
                dge.impDGrd();
                cxCompQuimica.setText("");
                cxCompQuimica.requestFocus();
                
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Formato Errado Informado", "Cadastro Mineral Precioso", 0);
             
        }
        precioso.setCertificado(cxCertificado.getText());
        precioso.setRefinamento(cxRefinamento.getText());
        precioso.getOrigem().setPais(cxPais.getText());
        precioso.getOrigem().setCidade(cxCidade.getText());
        precioso.getOrigem().setTipo_Extracao(cxTipExtracao.getText());
        
        precioso=bdMPrec.cadMPrecioso(precioso);
        if(precioso != null){
            JOptionPane.showMessageDialog(null, "Casdastro Realizado", "Cadastro Mineral Precioso", 1);
            limpar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Mineral com esse Codigo, ja existe", "Cadastro Mineral Precioso", 0);
        }
    }
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseje Sair","Sair", JOptionPane.YES_NO_CANCEL_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrecioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrecioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrecioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrecioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrecioso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfOrigem;
    private javax.swing.JLabel LCertificado;
    private javax.swing.JLabel LCompQuimica;
    private javax.swing.JLabel LCor;
    private javax.swing.JLabel LDureza;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LPais;
    private javax.swing.JLabel LPeso;
    private javax.swing.JLabel LRefinamento;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JLabel LValorComercial;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCertificado;
    private javax.swing.JTextField cxCidade;
    private javax.swing.JTextField cxCodIdentificador;
    private javax.swing.JTextField cxCompQuimica;
    private javax.swing.JTextField cxCor;
    private javax.swing.JTextField cxDureza;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxPais;
    private javax.swing.JTextField cxPeso;
    private javax.swing.JTextField cxRefinamento;
    private javax.swing.JTextField cxTipExtracao;
    private javax.swing.JTextField cxValorComercial;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrecioso;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbTipExtracao;
    private javax.swing.JLabel lblCodIdentificador;
    // End of variables declaration//GEN-END:variables
}
