
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class FormNaoMetalico extends javax.swing.JFrame {
    private MineralNaoMetalico n_metalico;
    private BDMineralNaoMetalico bdMNMet = new BDMineralNaoMetalico();
    /**
     * Creates new form FormPrecioso
     */
    public FormNaoMetalico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTitulo = new javax.swing.JLabel();
        lblCodIdentificador = new javax.swing.JLabel();
        cxCodIdentificador = new javax.swing.JTextField();
        LNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        LCor = new javax.swing.JLabel();
        cxCor = new javax.swing.JTextField();
        LCompQuimica = new javax.swing.JLabel();
        cxCompQuimica = new javax.swing.JTextField();
        LDureza = new javax.swing.JLabel();
        cxDureza = new javax.swing.JTextField();
        LPeso = new javax.swing.JLabel();
        cxPeso = new javax.swing.JTextField();
        LValorComercial = new javax.swing.JLabel();
        cxValorComercial = new javax.swing.JTextField();
        LCertificado = new javax.swing.JLabel();
        cxTransparencia = new javax.swing.JTextField();
        LRefinamento = new javax.swing.JLabel();
        cxIsolamento = new javax.swing.JTextField();
        InfOrigem = new javax.swing.JLabel();
        LPais = new javax.swing.JLabel();
        cxPais = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        cxCidade = new javax.swing.JTextField();
        lbTipExtracao = new javax.swing.JLabel();
        cxTipExtracao = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNMetalico = new javax.swing.JTable();
        jButtonAlterar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LTitulo.setText("Cadastra Mineral Não Metálico");

        lblCodIdentificador.setText("Codigo Identificador");

        cxCodIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCodIdentificadorActionPerformed(evt);
            }
        });

        LNome.setText("Nome");

        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        LCor.setText("Cor");

        cxCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCorActionPerformed(evt);
            }
        });

        LCompQuimica.setText("Composicao Química");

        cxCompQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCompQuimicaActionPerformed(evt);
            }
        });

        LDureza.setText("Dureza");

        cxDureza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDurezaActionPerformed(evt);
            }
        });

        LPeso.setText("Peso");

        cxPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPesoActionPerformed(evt);
            }
        });

        LValorComercial.setText("Valor Comercial");

        cxValorComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxValorComercialActionPerformed(evt);
            }
        });

        LCertificado.setText("Transparencia");

        cxTransparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTransparenciaActionPerformed(evt);
            }
        });

        LRefinamento.setText("Isolamento");

        cxIsolamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxIsolamentoActionPerformed(evt);
            }
        });

        InfOrigem.setText("Informações de Origem");

        LPais.setText("País");

        cxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPaisActionPerformed(evt);
            }
        });

        lbCidade.setText("Cidade");

        cxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCidadeActionPerformed(evt);
            }
        });

        lbTipExtracao.setText("Tipo de Extração");

        cxTipExtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTipExtracaoActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("Consultar pelo Codigo Identificador");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jTableNMetalico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Identificador", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        jScrollPane1.setViewportView(jTableNMetalico);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButton2.setText("Execluir pelo Codigo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LValorComercial)
                                .addComponent(LDureza)
                                .addComponent(LPeso)
                                .addComponent(LCor)
                                .addComponent(LNome)
                                .addComponent(lblCodIdentificador)
                                .addComponent(cxValorComercial, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addComponent(cxPeso)
                                .addComponent(cxDureza)
                                .addComponent(cxCompQuimica)
                                .addComponent(cxCor)
                                .addComponent(cxNome)
                                .addComponent(cxCodIdentificador))
                            .addComponent(LCompQuimica))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LPais)
                                                    .addComponent(lbCidade)
                                                    .addComponent(lbTipExtracao))
                                                .addGap(177, 177, 177))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LCertificado)
                                                    .addComponent(LRefinamento))
                                                .addGap(196, 196, 196)))
                                        .addComponent(cxTransparencia)
                                        .addComponent(cxPais)
                                        .addComponent(cxCidade)
                                        .addComponent(cxTipExtracao)
                                        .addComponent(cxIsolamento))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btCadastrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonAlterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(InfOrigem)
                                .addGap(102, 102, 102))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LTitulo)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTitulo)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LCertificado)
                        .addGap(4, 4, 4)
                        .addComponent(cxTransparencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LRefinamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxIsolamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InfOrigem))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(cxCodIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCodIdentificador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LCor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LCompQuimica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxCompQuimica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LPeso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LDureza)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cxDureza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(LValorComercial)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cxValorComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btLimpar)
                                    .addComponent(btCadastrar)
                                    .addComponent(btSair)
                                    .addComponent(jButtonAlterar)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LPais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbCidade)
                                .addGap(4, 4, 4)
                                .addComponent(cxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTipExtracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxTipExtracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPaisActionPerformed

    private void cxCodIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCodIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCodIdentificadorActionPerformed

    private void cxCompQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCompQuimicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCompQuimicaActionPerformed

    private void cxCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCorActionPerformed

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void cxIsolamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxIsolamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxIsolamentoActionPerformed

    private void cxTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTransparenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxTransparenciaActionPerformed

    private void cxValorComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxValorComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxValorComercialActionPerformed

    private void cxPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPesoActionPerformed

    private void cxDurezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDurezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDurezaActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrar();
        listarTab();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void cxTipExtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTipExtracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxTipExtracaoActionPerformed

    private void cxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCidadeActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        alterar();
        listarTab();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        excluirCod();
        listarTab();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void excluirCod(){
        n_metalico= new MineralNaoMetalico();
        try{
        n_metalico.setCodIdentificador(Integer.parseInt(cxCodIdentificador.getText()));
        n_metalico=bdMNMet.remvMNMetalico(n_metalico);
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Formato Errado Informado", "Cadastro Mineral Precioso", 0);    
        }
    }
    public void alterar(){
        n_metalico = new MineralNaoMetalico();
        
        try{
            n_metalico.setCodIdentificador(Integer.parseInt(cxCodIdentificador.getText()));
            n_metalico=bdMNMet.atualN_metalico(n_metalico);
            if(n_metalico != null){
                cxCodIdentificador.setText(Integer.toString(n_metalico.getCodIdentificador()));
                cxNome.setText(n_metalico.getNome());
                JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso", "Atualizar Dados", 1);
                
            }
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Formato Errado Informado", "Cadastro Mineral Precioso", 0);    
        }
    }
    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) jTableNMetalico.getModel();
        
        int posLin=0;
        
        modelo.setRowCount(posLin);
        
        for(MineralNaoMetalico n_metalico : bdMNMet.getBdMNMeta()){
            modelo.insertRow(posLin, new Object[]{
                n_metalico.getCodIdentificador(),
                n_metalico.getNome(),
                n_metalico.getCor(),
                n_metalico.getComposicaoQuimica(),
                n_metalico.getDureza(),
                n_metalico.getPeso(),
                n_metalico.getValorComercial(),
                n_metalico.getTransparencia(),
                n_metalico.getIsolamento(),
                n_metalico.getOrigem().getPais(),
                n_metalico.getOrigem().getCidade(),
                n_metalico.getOrigem().getTipo_Extracao(),
            });
            posLin++;
        }
    }
    public void limpar(){
        cxCodIdentificador.setText("");
       cxNome.setText("");
       cxCor.setText("");
       cxCompQuimica.setText("");
       cxDureza.setText("");
       cxPeso.setText("");
       cxValorComercial.setText("");
       cxTransparencia.setText("");
       cxIsolamento.setText("");
       cxPais.setText("");
       cxCidade.setText("");
       cxTipExtracao.setText("");
       cxCodIdentificador.requestFocus();
    }    
    public void cadastrar(){
        n_metalico=  new MineralNaoMetalico();
        
        n_metalico.setCodIdentificador(Integer.parseInt(cxCodIdentificador.getText()));
        n_metalico.setNome(cxNome.getText());
        n_metalico.setCor(cxCor.getText());
        try{
                n_metalico.setComposicaoQuimica(cxCompQuimica.getText());
                n_metalico.setDureza(Integer.parseInt(cxDureza.getText()));
                n_metalico.setPeso(Float.parseFloat(cxPeso.getText()));
                n_metalico.setValorComercial(Double.parseDouble(cxValorComercial.getText()));
        }
        catch(ComposicaoQGrdException cge){
                cge.impCQGrd();
                
        }
        catch(DurezaPqnException dpe){
                dpe.impDPqn();
                
        }
        catch(DurezaGrdException dge){
                dge.impDGrd();
                cxCompQuimica.setText("");
                cxCompQuimica.requestFocus();
                
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Formato Errado Informado", "Cadastro Mineral Precioso", 0);
             
        }
        n_metalico.setTransparencia(cxTransparencia.getText());
        n_metalico.setIsolamento(cxIsolamento.getText());
        n_metalico.getOrigem().setPais(cxPais.getText());
        n_metalico.getOrigem().setCidade(cxCidade.getText());
        n_metalico.getOrigem().setTipo_Extracao(cxTipExtracao.getText());
        
        n_metalico=bdMNMet.cadMNMetalico(n_metalico);
        if(n_metalico != null){
            JOptionPane.showMessageDialog(null, "Casdastro Realizado", "Cadastro Mineral Precioso", 1);
            limpar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Mineral com esse Codigo, ja existe", "Cadastro Mineral Precioso", 0);
        }
    }
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseje Sair","Sair", JOptionPane.YES_NO_CANCEL_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrecioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrecioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrecioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrecioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNaoMetalico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfOrigem;
    private javax.swing.JLabel LCertificado;
    private javax.swing.JLabel LCompQuimica;
    private javax.swing.JLabel LCor;
    private javax.swing.JLabel LDureza;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LPais;
    private javax.swing.JLabel LPeso;
    private javax.swing.JLabel LRefinamento;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JLabel LValorComercial;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCidade;
    private javax.swing.JTextField cxCodIdentificador;
    private javax.swing.JTextField cxCompQuimica;
    private javax.swing.JTextField cxCor;
    private javax.swing.JTextField cxDureza;
    private javax.swing.JTextField cxIsolamento;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxPais;
    private javax.swing.JTextField cxPeso;
    private javax.swing.JTextField cxTipExtracao;
    private javax.swing.JTextField cxTransparencia;
    private javax.swing.JTextField cxValorComercial;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNMetalico;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbTipExtracao;
    private javax.swing.JLabel lblCodIdentificador;
    // End of variables declaration//GEN-END:variables
}
